feat: batch API for historical, aggregated, and latest value data
awslabs/iot-app-kit pull request #137
Opened 2022-06-29 17:44 UTC by boweihan

## Overview
Merging `feature-batch` into mainline.

Switch from using single asset property APIs to batch APIs for fetching time-series data. Widget requests are batched on a per-tick basis by default, with the option of configuring a custom batch duration. 

Associated PRs:
https://github.com/awslabs/iot-app-kit/pull/130 - documentation
https://github.com/awslabs/iot-app-kit/pull/128 - batchDuration setting
https://github.com/awslabs/iot-app-kit/pull/125 - latest value batching
https://github.com/awslabs/iot-app-kit/pull/114 - aggregated data batching
https://github.com/awslabs/iot-app-kit/pull/108 - edge case handling for historical data batching
https://github.com/awslabs/iot-app-kit/pull/102 - historical data batching
https://github.com/awslabs/iot-app-kit/pull/101 - dataloader proxy

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2022-06-30 15:38 UTC, diehbria requested changes

2022-06-30 15:42 UTC, diehbria commented on docs/AWSIoTSiteWiseSource.md
> +`batchDuration`
the preceding paragraph should be re-arranged a little. The very first word should be (Optional) [basic description]

2022-06-30 15:43 UTC, diehbria requested changes
Comments on documentation for consistency

2022-07-08 18:17 UTC, NorbertNader commented on packages/components/src/testing/testing-ground/testing-ground.tsx
> +              widgetId="kpi-1"
nit: scatter

2022-07-08 18:17 UTC, NorbertNader commented on packages/components/src/testing/testing-ground/testing-ground.tsx
> +              widgetId="kpi-1"
nit: line

2022-07-12 00:59 UTC, NorbertNader approved these changes

2022-07-12 13:55 UTC, merged