feat(dashboard): add api for customizing the properties panel
awslabs/iot-app-kit pull request #1445
Opened 2023-06-02 20:56 UTC by jmbuss

## Overview
Adds a configuration option in dashboard to customize the properties panel sections.

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2023-06-02 21:46 UTC, mnischay commented on packages/dashboard/src/components/internalDashboard/index.tsx
> +        // rightPane={<SidePanelOld messageOverrides={DefaultDashboardMessages} />}
you can probably remove this ?

2023-06-02 21:46 UTC, mnischay commented on packages/dashboard/src/customization/propertiesSection.tsx
> +function compositeValue<T>(values: T[]): Maybe<T> {
super nit: better to use arrow function?

2023-06-02 21:46 UTC, mnischay commented on packages/dashboard/src/customization/propertiesSection.tsx
> +  const type = compositeValue(selection.map((w) => w.type));
super nit: typically we avoid alphabets as variable names ?

2023-06-02 21:46 UTC, mnischay commented on packages/dashboard/src/customization/propertiesSection.tsx
> +export const isDashboardWidget = (w: DashboardWidget): w is DashboardWidget => !!w;
curious : is it ok if we dont use alphabets ? may be its a personal pref..

2023-06-02 21:46 UTC, mnischay commented on packages/dashboard/src/customization/propertiesSections/shared/selectOneWidget.tsx
> +export const SelectOneWidget: React.FC = () => (
nit: given no props, do we need ```React.FC``` ?

2023-06-02 21:46 UTC, mnischay commented on packages/dashboard/src/customization/propertiesSections/textSettings/text.tsx
> +  fontColor = '#000000',
may be should use cloudscape design token ?

2023-06-05 19:08 UTC, jmbuss commented on packages/dashboard/src/customization/propertiesSection.tsx
> +      propertyValue,
The sections do determine this. `useSelection` returns a hook called `useProperty` That hook is used in each section to get / set those properties

2023-06-06 19:43 UTC, tracy-french requested changes
Great work, @jmbuss! This is a foundational change for the dashboard and I think you nailed it. Before we merge this in, let's add plenty of in-source documentation. It's complex, yet fundamental. Let's make it super easy to build with. :)

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/components/propertiesPanel/index.tsx
> +const SidePanel: React.FC<SidePanelProps> = ({ sections }) => {
Why type `React.FC<Props>` and not type the props?

```ts
const SidePanel = ({ sections }: SidePanelProps) => { [..] };
```

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSection.tsx
> +) => React.ReactElement;
These and other types in this file could benefit from doc comments.

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSection.tsx
> +   * TECH DEBT: getSelectionBox should never be null given the above check
Great comment!

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSections/axisSettings/index.tsx
> +const axisWidgetTypesThatSupportYAxis: readonly string[] = ['line-chart', 'scatter-chart', 'bar-chart'];
Nice usage of readonly!

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/section.tsx
> +export const TablePropertiesAlarmsSection: FC<TablePropertiesAlarmsSectionProps> = ({
Formatting! :p

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSections/propertiesAndAlarmsSettings/section.tsx
> +export const GeneralPropertiesAlarmsSection: FC<PropertiesAlarmsSectionProps> = ({
This component and file would benefit from comments.

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSections/shared/useExpandable.ts
> +  return [expanded, setExpanded] as const;
Nice!

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSections/shared/useExpandable.ts
> +  }, [syncCloseWhen]);
Is the effect necessary?

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSections/sizeAndPositionSettings/section.spec.tsx
> +import { SizeAndPositionConfiguration } from './index';
How do we order our imports?

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSections/thresholdSettings/index.tsx
> +
Do we need all these utilities for this component?

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSections/thresholdSettings/thresholdsSection.tsx
> +import React, { FC, MouseEventHandler } from 'react';
This file would benefit from comments. There's a lot going on here.

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/util/maybe.ts
> +};
If you make a public util, treat it like an API and document its intended usage.

2023-06-06 19:43 UTC, tracy-french commented on packages/dashboard/src/customization/propertiesSections/textSettings/index.tsx
> +export const TextSettingsConfiguration: React.FC = () => (
Looks clean!

2023-06-13 19:53 UTC, corteggiano approved these changes

2023-06-14 15:03 UTC, tracy-french approved these changes
Fantastic work @jmbuss! Thank you for increasing the extensibility of the dashboard with your contribution!

2023-06-14 17:13 UTC, merged