Npm workspaces
awslabs/iot-app-kit pull request #203
Opened 2022-08-11 18:48 UTC by TheEvilDev

## Overview
Removes dev dependencies on `yarn` and `lerna` and just uses npm workspaces.

## Tests
[Include a link to the passing GitHub action running the test suite here.]

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2022-08-11 19:24 UTC, boweihan requested changes
There are a few instances of documentation that still use yarn commands - for example, `docs/GettingStarted.md`, `README.md`, and our `npm-publish.yml` workflow. Could probably just do a global find and replace for these instances.

2022-08-11 19:24 UTC, boweihan commented on docs/development.md
> +Alter the file `siteWiseQueries` within `@iot-app-kit/components` to point to valid SiteWise asset properties for the accounts credentials from the prior step.
dunno if it's just GH, but the spacing of these descriptions look inconsistent (new line here, vs. tab above and below).

2022-08-11 19:24 UTC, boweihan commented on docs/development.md
>  Iot-App-Kit runs on node and uses yarn for package management. Specific versions are required in order to keep builds working with the current monorepo tooling.
Remove yarn from this statement

2022-08-11 21:08 UTC, diehbria commented
make sure to clean up the commit history (which is considered part of the review)

2022-09-06 14:53 UTC, boweihan commented
Closing this and rolling it into https://github.com/awslabs/iot-app-kit/pull/231

2022-09-06 14:53 UTC, closed without merging