fix: style updates and bugfixes for multi y axis
awslabs/iot-app-kit pull request #2039
Opened 2023-10-04 20:57 UTC by jmbuss

## Overview
Bugfix for multi y axis not a number display.

Style fixes for multi y axis legend. Fix spacing and font sizing.

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2023-10-05 12:07 UTC, tracy-french approved these changes

2023-10-05 12:12 UTC, tracy-french commented
Looks good!

2023-10-05 12:23 UTC, mnischay approved these changes

2023-10-05 14:20 UTC, diehbria requested changes
just a comment on the aesthetics:

pulled locally - aesthetics still do not match - need smaller font, smaller spacings around the "color bar". current implementation leads to lots of text-overflow making it so y-axis values aren't visible, and don't have units for context
<img width="142" alt="Screenshot 2023-10-05 at 7 19 16 AM" src="https://github.com/awslabs/iot-app-kit/assets/77755322/a4d867ae-14a5-4261-998e-ba1c72cc5ad8">

2023-10-06 17:27 UTC, diehbria approved these changes

2023-10-11 17:02 UTC, closed without merging