feat: dashboard widget panel fit and finish 2306
awslabs/iot-app-kit pull request #2077
Opened 2023-10-11 10:12 UTC by Priyanshu44

![image](https://github.com/awslabs/iot-app-kit/assets/81667589/bbaef516-99b1-4d52-9937-cf644d128a82)

Issue: https://github.com/awslabs/iot-app-kit/issues/2036

Description: Added "Widgets" text with horizontal divider to the Widget library panel on the dashboard.

Changes in the CR:
-> Added "Widgets" text with mentioned font design with a right divider of 2px.
->Added bottom border, 2px grey-200

2023-10-11 14:45 UTC, mnischay submitted a review, later dismissed

2023-10-11 15:11 UTC, tracy-french submitted a review, later dismissed

2023-10-11 18:11 UTC, tracy-french commented
One of the status checks is stuck and there's a message at the top about "Processing updates". Will check in later to check if it can be merged.

2023-10-12 14:49 UTC, corteggiano commented on packages/react-components/src/components/chart/utils/getXAxis.ts
> +    max: viewportInMs.isDurationViewport ? viewportInMs.end : undefined,
does this break gesturing? specifically scrolling to the left and right on the charts

2023-10-16 13:57 UTC, mnischay requested changes
something is messed with the CR, it has unrealted changes

2023-10-16 13:57 UTC, mnischay commented on .github/workflows/codeql-analysis.yml
> +    branches: [ main, rc ]
these changes are already in the rc branch ?

2023-10-16 14:35 UTC, closed without merging

2023-10-16 14:48 UTC, Priyanshu44 commented
Resolved conflict

2023-10-16 14:49 UTC, Priyanshu44 commented
Resolved conflict