Feature/dial
awslabs/iot-app-kit pull request #222
Opened 2022-08-30 10:46 UTC by jiaoyangChen

## Overview
Provide an explanation of what the change is

## Tests
[Include a link to the passing GitHub action running the test suite here.]

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2022-10-01 02:14 UTC, NorbertNader commented on packages/components/src/components/iot-dial/iot-dial.spec.ts
> +const kpiSpecPage = async (propOverrides: Partial<Components.IotKpi> = {}) => {
nit: dial

2022-10-09 11:20 UTC, jiaoyangChen commented on packages/components/src/components/iot-dial/iot-dial.spec.ts
> +const kpiSpecPage = async (propOverrides: Partial<Components.IotKpi> = {}) => {
Done

2022-10-11 17:34 UTC, diehbria requested changes
Please always add an explanation of what this review in the overview, as mentioned previously.

Also the PR is quite large because it's also rebasing. Could you make a seperate PR which all it does it brings`feature-dial-gauge` to be rebased to `main`, so we can seperate out the new work vs rebase

2022-10-13 10:32 UTC, jiaoyangChen commented on packages/components/src/components/iot-dial/iot-dial.tsx
> +            const yMin = (this.styleSettings?.yMin || this.viewport.yMin) as number;
It will add `|| 0`.

2022-10-13 10:33 UTC, jiaoyangChen commented on packages/components/src/components/iot-dial/iot-dial.tsx
> +            console.log(JSON.stringify(dataStream), 'datastream');
Done

2022-10-13 10:35 UTC, jiaoyangChen commented
> Please always add an explanation of what this review in the overview, as mentioned previously.
> 
> Also the PR is quite large because it's also rebasing. Could you make a seperate PR which all it does it brings`feature-dial-gauge` to be rebased to `main`, so we can seperate out the new work vs rebase

I will split into 5 pr submissions.
The first pr is merge main https://github.com/awslabs/iot-app-kit/pull/277.

2022-11-02 19:59 UTC, TheEvilDev commented
Please recreate this pull request off the new head, a history rewrite was pushed. Closing.

2022-11-02 19:59 UTC, closed without merging