feat(component, table): switch to cloudscape for table component
awslabs/iot-app-kit pull request #224
Opened 2022-08-31 15:40 UTC by square-li

## Overview
- `package/table`
  - replace `@awsui/components-react` with `@cloudscape-design/components`
- `package/components`
  - add imports cloudscape's style sheets to component package
  - update stencil config for testing
  - update change logs

## Tests
[Include a link to the passing GitHub action running the test suite here.]

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2022-08-31 22:34 UTC, diehbria commented
add scope to the commit message as according to conventional commit

2022-08-31 22:34 UTC, diehbria requested changes

2022-08-31 22:34 UTC, diehbria commented on packages/components/src/styles/cloudscape.css
> +@import "~@cloudscape-design/global-styles/index.css";
is there a way we can do this that is better from a code splitting perspective?

2022-09-01 15:27 UTC, square-li commented
We decided to not move forward with cloudscape at this moment. Closing.

2022-09-01 15:27 UTC, closed without merging