feat(dashboard): composite API calls to list composite asset properties
awslabs/iot-app-kit pull request #2262
Opened 2023-11-10 22:40 UTC by ssjagad

## Overview
Provide an explanation of what the change is

## Verifying Changes

### Scene Composer
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To do this, wait for the `Publish Storybook` action to complete below.

- Click on the workflow details
- Select the Summary item on the left
- Download the zip file

To run the storybook build locally, you need a local static web server:

```
npm install -g httpserver
cd <Extracted Zip Directory>
httpserver
```

Then open the website http://localhost:8080 to run the doc site.

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2023-11-13 16:26 UTC, tracy-french requested changes
Looks good overall, @ssjagad. There are a few items we should address before merging this in, primarily with naming and TypeScript semantics/best practices.

2023-11-13 16:26 UTC, tracy-french commented on packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/types.ts
> +type listPropertyOutputExtender = {
Types should be written in pascal case, such as `ListPropertyOutputExtender`.

2023-11-13 16:26 UTC, tracy-french commented on packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/types.ts
> +export type SelectedAssetsPropsArray = SelectedAssetProp[];
Can this just be `SelectedAsset`? Appending `Prop` to the end doesn't seem to add meaning and may actually add confusion.

2023-11-13 16:26 UTC, tracy-french commented on packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/useModeledDataStreams/useModeledDataStreams.ts
> +      queries: assetProps.map((assetProperties) => ({
You called the item `assetProperties`, yet it does not appear we are iterating over asset properties.

2023-11-13 16:26 UTC, tracy-french commented on packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/types.ts
> +type listPropertyOutputExtender = {
Also, `Extender` sounds like it performs an action, yet this construct has no methods on it. What about something like `ExtendedAssetPropertySummaryProperties`?

2023-11-13 16:26 UTC, tracy-french commented on packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/types.ts
> +export type SelectedAssetsPropsArray = SelectedAssetProp[];
Generally, you should avoid `Array` types in TypeScript. They don't offer much value. Instead, just annotate types as `SelectedAssetProp[]` as needed.

2023-11-13 16:26 UTC, tracy-french commented on packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/useModeledDataStreams/listModeledDataStreamsRequest.ts
> +} from '../../types';
Ensure you use type imports when importing types.

2023-11-13 16:26 UTC, tracy-french commented on packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/modeledDataStreamQueryEditor/modeledDataStreamExplorer/useModeledDataStreams/useModeledDataStreams.ts
> +    const request = new ListModeledDataStreamsRequest({ assetProp: assetProperties.assetProp, client, signal });
By destructuring the queryKey in the function parameters, such as `queryKey: [{ assetProp }]`, you can change the request to `const request = new ListModeledDataStreamRequest({ assetProp, client, signal });` and make things a little cleaner. :)

2023-11-24 21:15 UTC, corteggiano approved these changes

2023-11-24 21:18 UTC, chejimmy submitted a review, later dismissed

2023-11-25 01:30 UTC, merged