feat: added the error state for resource explorer tables
awslabs/iot-app-kit pull request #2296
Opened 2023-11-23 11:22 UTC by Chandru-HM

## Overview
This PR is for ticket (a few sub tasks are covered here(3, 4 & 5)) #2242 and to update error state in Resource explorer tables
1. added error state for browse assets table
2. added error state for browse datastream table
3. added error state for search datastream table

## Verifying Changes
![assets-error](https://github.com/awslabs/iot-app-kit/assets/142866907/5ca3de71-32f3-441a-9e44-81a1fbcb4c9b)
![datastream-error](https://github.com/awslabs/iot-app-kit/assets/142866907/07d69b96-9e78-4ed8-9765-6c6e3514fccd)
![search-error](https://github.com/awslabs/iot-app-kit/assets/142866907/5f44b3f2-0e35-4a26-b850-6d0bdff83adc)

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2023-11-27 06:52 UTC, Chandru-HM commented
> The header above the Alert is missing in this CR ? --> "Search Result for "Query"" or is it not part of AC in the sub tasks ?

updated.

2023-11-28 10:24 UTC, mnischay requested changes
code change LGTM, just a small naming change request

2023-11-28 10:24 UTC, mnischay commented on packages/dashboard/src/components/queryEditor/helpers/resourceExplorerErrorState.tsx
> +import React from 'react';
the folder name seems to be not super appropriate... these is a component... helpers seems like utility functions.... probably just components might make sense ?

2023-11-28 22:58 UTC, tracy-french approved these changes
Looks like the change has been made. Based on Nischay's guidance that the code looks good and that the requested change was made, I will approve and merge to move this allow.

2023-11-28 22:59 UTC, merged