fix(react-components): trendcursor hotkey indicates addition state
awslabs/iot-app-kit pull request #2303
Opened 2023-11-27 23:07 UTC by ssjagad

## Overview
The trend cursor hotkey (T key) did not specify that the user was in a state to add a TC. To fix this, we change the cursor to a cross hair cursor on keydown and reset the cursor  to pointer when the TC is added. This way, clicking the T key has a clear workflow for users. 

Updated useTrendCursorEvents.spec to reflect code changes by mocking call to useState function that sets the TC addition state to false.

## Verifying Changes

https://github.com/awslabs/iot-app-kit/assets/145582655/c99a84c0-bdb3-4b09-8704-0ee376ec3683

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2023-11-28 04:44 UTC, mnischay requested changes
I dont think the below changes will fix the issue, right now , mouseMoveEventHandler is when the cursor style is set, instead it should on the `isInCursorAddMode === true`

2023-11-28 16:39 UTC, ssjagad commented
> I dont think the below changes will fix the issue, right now , mouseMoveEventHandler is when the cursor style is set, instead it should on the `isInCursorAddMode === true`

Good point. I had it change to cross hair on mouse move. Added that check and it should be good :)

2023-11-29 13:02 UTC, mnischay commented on packages/react-components/src/components/chart/trendCursor/mouseEvents/useTrendCursorsEvents.ts
> +          setIsInCursorAddModeRef.current(false); // change cursor back to regular from cross hair (hotkeys)
this should be added after the else loop...

2023-11-29 13:20 UTC, mnischay requested changes
I think you are missing the RC of the issue...
We are showing the cross hair on the mousemove event... but when the user
1. presses the t button AND
2. does not move the mouse
even though we are in "add" mode, the mouse does not reflect it.. 

So the solution would to make the "change in cursor style"  not dependent on the mouse but instead make it dependent on 
(ignoreHotKey || isInCursorAddModeRef.current) && graphicRef.current.length < MAX_TREND_CURSORS

i.e when we allow the user to add a TC

2023-11-29 13:20 UTC, mnischay commented on packages/react-components/src/components/chart/trendCursor/useTrendCursors.ts
> +    commandDown: () => {
I am not sure why commandUp was removed.... if the user continues to hold T, we should keep them in the add mode as long as that ?

2023-11-29 13:20 UTC, mnischay commented on packages/react-components/src/components/chart/trendCursor/mouseEvents/useTrendCursorsEvents.ts
> +          setIsInCursorAddModeRef.current(false); // change cursor back to regular from cross hair (hotkeys)
Also, why forcefully stop the add mode ? like user is still holding the t ... and we are kicking them out of the add mode ?

2023-12-04 14:45 UTC, ssjagad commented on packages/react-components/src/components/chart/trendCursor/mouseEvents/useTrendCursorsEvents.ts
> +    const mouseMoveEventHandler = () => mouseoverHandler(isInCursorAddModeRef.current, graphicRef.current, chartRef);
updated video to show this

2023-12-06 16:29 UTC, mnischay approved these changes

2023-12-06 16:29 UTC, merged