feat: when scatter chart is selected the line style dropdown should b…
awslabs/iot-app-kit pull request #2432
Opened 2023-12-29 13:32 UTC by Priyanshu44

Issue: https://github.com/awslabs/iot-app-kit/issues/2427

Verification:
[disable-style.webm](https://github.com/awslabs/iot-app-kit/assets/81667589/0bd74bcf-2251-4639-9902-dbb66ca4992b)

Fix:
-> when scatter chart is selected the line style dropdown should be none and disabled

2023-12-29 15:57 UTC, mnischay requested changes
The testing video attached does not show the AC.. the chart type is non-scatter but the line style is disabled .... which is not what we want

2023-12-29 17:10 UTC, Priyanshu44 commented
> The testing video attached does not show the AC.. the chart type is non-scatter but the line style is disabled .... which is not what we want

Updated the video and changes.

2024-01-08 16:52 UTC, mnischay requested changes
looks like you have done per property but not at widget level

2024-01-22 14:44 UTC, mnischay approved these changes

2024-01-22 14:44 UTC, merged