fix: template asset table disables invalid dataTypes
awslabs/iot-app-kit pull request #2485
Opened 2024-01-17 18:16 UTC by corteggiano

Templating/Dynamic Assets table disables a property if its dataType is not supported given the selected widget
---
![Screenshot 2024-01-17 at 11 13 13](https://github.com/awslabs/iot-app-kit/assets/28601414/b6a4909b-e906-4ec6-a3a4-b44b1d51b002)

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2024-01-17 21:01 UTC, corteggiano commented on packages/dashboard/e2e/tests/resourceExplorer/resourceExplorer.spec.ts
> -  await selectProperty('Coordinates');
Coordinates was a string property so it should not work with a line chart

2024-01-17 22:42 UTC, tracy-french requested changes

2024-01-17 22:42 UTC, tracy-french commented on packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelPropertiesExplorer/assetModelPropertiesTable/assetModelPropertiesTable.tsx
> +} from '@aws-sdk/client-iotsitewise';
Nit: Prefer type imports.

2024-01-17 22:42 UTC, tracy-french commented on packages/dashboard/src/components/queryEditor/iotSiteWiseQueryEditor/assetModelDataStreamExplorer/assetModelPropertiesExplorer/assetModelPropertiesTable/assetModelPropertiesTable.tsx
> +          item.dataType as NonNullable<PropertyDataType | undefined>,
Nit: Can you instead use a type annotation?

```
isItemDisabled={(item: NonNullable<PropertyDataType | undefined>) => 
```

2024-01-17 22:42 UTC, tracy-french commented on packages/dashboard/e2e/tests/resourceExplorer/resourceExplorer.spec.ts
> -  await expect(grid.gridArea().getByText('Coordinates')).toBeVisible();
Could you add a test to ensure properties of types a chart does not support cannot be added? This will ensure we won't regress the behavior.

2024-01-18 16:49 UTC, tracy-french approved these changes

2024-01-18 16:49 UTC, merged