feat: conditionally display latest value in legend table
awslabs/iot-app-kit pull request #2522
Opened 2024-01-29 08:38 UTC by Chandru-HM

## Overview
This PR is for ticket #2277  and implemented display latest value feature and it includes
1. default display property latest value is true
2. user can toggle the display latest value in the config legend section

## Verifying Changes
[latestvalue-in-legend.webm](https://github.com/awslabs/iot-app-kit/assets/142866907/98c17ee0-c639-41a4-a912-c2a6bb62afdd)

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2024-01-31 11:56 UTC, gmuralidharreddy commented
LGTM

2024-02-05 23:24 UTC, tracy-french requested changes
See internal Slack thread. I think we can avoid extending `DataStream`.

2024-02-06 12:14 UTC, Chandru-HM commented
> See internal Slack thread. I think we can avoid extending `DataStream`.

updated.

2024-02-16 16:50 UTC, corteggiano approved these changes
verified manually and reviewed code 👍 LGTM

2024-02-16 16:50 UTC, merged