chore: add examples of refId style object to docsite
awslabs/iot-app-kit pull request #2775
Opened 2024-05-03 18:00 UTC by ssjagad

## Overview
- Added missing name property to the style settings object docs
- Added two examples of how to use the style settings object, one a simple name and color property change and one that details line style changes

## Verifying Changes
- should show up on the docsite itself

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2024-05-07 22:23 UTC, diehbria requested changes

2024-05-07 22:23 UTC, diehbria commented on packages/doc-site/stories/components/chart/Docs.mdx
> +Simple way to set the color and name of the property in the line chart. This one will color the property red on the cahrt and display it as 'Demo Property'.
misspelled chart

2024-05-08 17:31 UTC, ssjagad commented on packages/doc-site/stories/components/chart/Docs.mdx
> +Simple way to set the color and name of the property in the line chart. This one will color the property red on the cahrt and display it as 'Demo Property'.
whoops, fixed!

2024-05-09 14:22 UTC, diehbria approved these changes

2024-05-09 16:09 UTC, merged