Opacity filter zero
awslabs/iot-app-kit pull request #342
Opened 2022-11-09 22:42 UTC by TheEvilDev

## Overview
Opacity filter was incorrectly showing objects when opacity was set to 0. This was a bug in the boolean logic to check if it should apply alpha or not.

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2022-11-09 23:03 UTC, jwills-jdubs submitted a review, later dismissed

2022-11-10 16:03 UTC, diehbria requested changes
make sure the commits follow conventional commit and that the PR is a request to merge one well formatted commit (commit message considered part of the review)

2022-11-10 16:08 UTC, diehbria approved these changes

2022-11-10 18:36 UTC, sheilaXu commented on packages/scene-composer/src/components/three-fiber/ColorOverlayComponent/index.tsx
> +            if ((ruleColor.alpha || ruleColor.alpha === 0) && ruleColor?.alpha !== 1) {
would it be more clear to combine the first 2 conditions into `isNumber(ruleColor.alpha)`?

2022-11-10 19:30 UTC, merged