fix(source-iotsitewise): deduplicate batch requests
awslabs/iot-app-kit pull request #629
Opened 2023-03-01 21:50 UTC by tjuranek

## Overview

Deduplicates individual requests in a batch in the `source-iotsitewise` package. This eliminates duplicate calls to sitewise for the same data, like when multiple charts are rendering the same data at once.

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2023-03-02 16:12 UTC, diehbria approved these changes

2023-03-02 18:19 UTC, diehbria requested changes
make sure to squash commits

2023-03-02 20:24 UTC, diehbria submitted a review, later dismissed

2023-03-03 15:42 UTC, corteggiano approved these changes

2023-03-03 15:46 UTC, merged