feat(Matterport): add Tag Sync button to setting
awslabs/iot-app-kit pull request #789
Opened 2023-03-22 19:51 UTC by haweston

## Overview
Add Tag Sync button to Matterport Settings panel in TwinMaker Scene Editor

## Verifying Changes
The scene viewer doesn't update as you change a Matterport scene so the easiest way to verify is:
Have a TwinMaker Scene with a fake Matterport Tag imported into already (tag with properties {matterportId: 'someId'} that isn't in your Matterport space
A Matterport space with 2+ tags
Use the Sync button -
 the fake Matterport tag should be deleted
 the other tags should get added
Manually delete a tag
Manually enter some data bindings on one of the new imported tags
Use the Sync button
Verify: the manually deleted tag returns, verify the added bindings aren't ovewritten when the tag updates

### Scene Composer
For `scene-composer` package changes specifically, you can preview the component in the published storybook artifact. To do this, wait for the `Publish Storybook` action to complete below.

- Click on the workflow details
- Select the Summary item on the left
- Download the zip file

To run the storybook build locally, you need a local static web server:

```
npm install -g httpserver
cd <Extracted Zip Directory>
httpserver
```

Then open the website http://localhost:8080 to run the doc site.

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

2023-03-23 16:36 UTC, haweston commented on packages/scene-composer/src/hooks/useMatterportTags.ts
> +      // rotate the point through x-axis by -90 degree
No it's not, which would be very confusing. it was from the old script and I had to change the code when I test it against the version in the matterport space.

2023-03-23 16:40 UTC, haweston commented on packages/scene-composer/src/hooks/useMatterportTags.ts
> +    type: 'Tag',
Cut and paste of old code, agree that's a better option.

2023-03-23 16:45 UTC, haweston commented on packages/scene-composer/src/hooks/useMatterportTags.ts
> +      scale: [1, 1, 1],
Tags don't support rotation currently, but they might. We keep waffling on scale.   I think you're right that we shouldn't reset them here I think as the matterport sync shouldn't be opinionated about customization of TwinMaker tags.

2023-03-23 16:48 UTC, haweston commented on packages/scene-composer/src/components/panels/scene-settings/MatterportTagSync.tsx
> +    }
We unfortunately can't, or not without doing unnecessary operations by merging two dictionaries.  mattertag and tag are different data types and in our test scene I've shown that one can be defined in a scene and the other undefined so we have to do each one depending what versions are used in the matterport space.

2023-03-23 19:32 UTC, haweston commented on packages/scene-composer/src/store/Store.ts
> +  setMatterportSdk: state.setMatterportSdk,
implemented

2023-03-23 23:11 UTC, sheilaXu approved these changes

2023-03-23 23:14 UTC, sheilaXu commented
Make sure to "**Squash and merge**" instead of "**Rebase and merge**", so we add single commit to the base branch

2023-03-23 23:44 UTC, sheilaXu requested changes
please squash all commit into a single one since we don't allow squash merging in the repo

2023-03-24 00:47 UTC, sheilaXu approved these changes

2023-03-24 01:06 UTC, merged